Support autotune
AyakaGEMM/Hands-on-MLIR pull request #2
Opened 2024-03-18 09:53 UTC by Pzzzzz5142

2024-03-18 10:12 UTC, umiswing requested changes

2024-03-18 10:18 UTC, Pzzzzz5142 commented on lib/ExecutionEngine/HandsOnNVGPURunnerUtils.cu
> +  return;
remove the debug code

2024-03-19 05:42 UTC, Pzzzzz5142 commented
The calculation issue should be fixed in #5.

2024-03-21 07:30 UTC, Pzzzzz5142 commented on include/NVGPUKernels/LayernormGemmRunner.h
> +    }
Unrelated to this pr.

2024-03-21 07:30 UTC, Pzzzzz5142 commented on include/NVGPUKernels/LayernormGemmRunner.h
> +  }
Fixed

2024-03-21 07:30 UTC, Pzzzzz5142 commented on include/NVGPUKernels/LayernormGemmRunner.h
> +      return op->update(args);
Fixed

2024-03-21 07:36 UTC, umiswing approved these changes

2024-03-21 07:37 UTC, merged